# Generated by Django 2.2 on 2021-07-08 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0002_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='name',
            new_name='stock_name',
        ),
    ]
