# Generated by Django 2.2 on 2021-07-08 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_auto_20210707_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='url',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
