# Generated by Django 2.2 on 2021-07-09 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0006_auto_20210708_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='article_users',
        ),
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='stock_app.Stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='user_articles', to='stock_app.User'),
            preserve_default=False,
        ),
    ]
