# Generated by Django 2.2 on 2021-07-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0008_auto_20210708_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='article_user',
        ),
    ]
